name: 'Compile Sourcepawn Plugin'
description: 'Compile sourcepawn plugins by using the latest sourcemod build of a selected version'
author: 'SheplyRam'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  input:
    description: 'path/to/plugin.sp to your plugin file.'
    required: true
  output:
    description: 'path/to/plugin.smx to output your compiled plugin file.'
    required: true
  sourcemod:
    description: 'Sourcemod version. It must bem 1.11 or 1.12'
    required: false
    default: '1.12'
  includes:
    description: 'path/to/include If your plugin has custom includes'
    required: false
    default: ''
  comp64:
    description: 'Tells if you want to use 32-bits or 64-bits compiler'
    required: false
    default: 'true'
outputs:
  result:
    description: 'The log output of the compilation'
runs:
  using: 'node16'
  main: lib/index.js
